spring:
  config:
    import: "optional:file:.env[.properties]" # make spring read from .env file
  application:
    name: shieldshare
  datasource:
    url: jdbc:postgresql://localhost:5432/shieldshare
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  database: postgresql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-on-migrate: true

server:
  servlet:
    context-path: /api/v1

app:
  size-caps:
    max-content-bytes: 1048576 # 1 MiB (content cap). used only for client-side UX only
    max-request-bytes: 1573000 # 1.5 MiB + headroom for base64 overhead, metadata, JSON envelope
    max-blob-bytes: 1052701 # 1 MiB + headroom (content, metadata, version byte, iv, GCM tag)
  encryption-version-byte: "0x00"
  ttl-options-seconds: "300,3600,86400,604800" # 5m, 1h, 24h, 7d